### ISSUE TITLE
Sorting event handling

### ISSUE THREAD

**Issue by LeilaMoussa** [Maxl94/ngx-multi-sort-table#85] opened 2022-08-16 00:41 UTC
Hello! I'm trying to use multi sort for my table, but I can't get a grip on event handling for sort change for some reason. Here's an example of my code: https://stackblitz.com/edit/angular-vf7brq-3ymnui?devToolsHeight=33&file=src/app/table-sorting-example.html

Clicking on the column headers doesn't trigger anything and I'm wondering how much of the event handling I should implement.

Note: I noticed the same thing about the original Stackblitz example for this package. Clicking on the column headers doesn't do any sorting the way the GIF shows. Pagination, however, seems fine.

Angular 8, ngx-mat-multi-sort 0.7.4.

Thanks!

**Comment by Maxl94** [comment] 2022-09-21 08:56
Hi, am sorry for the late response. 

I am not able to reproduce the issue. I can, it is not working on stackblitz. 
Since I can not provide support for older versions, I recommend you to update the package to current version. 

Let me know if the error still exist.

**Comment by LeilaMoussa** [comment] 2022-09-21 12:34
HI, we figured out it was a version issue. On Angular 8, installing the package from npm did not work, but manually copying the library into our project worked fine. We're thinking it should be okay on Angular 13. Thanks!

**Comment by Maxl94** [comment] 2022-09-23 08:10
Thanks for the feedback, then I will close the issue.

**Closed by Maxl94** 2022-09-23 08:10 UTC
